// Fine-grained industry sector per symbol (pre-2026-08-06 taxonomy), kept
// ONLY for momentumScore.js's RS-vs-sector calculation — marketStore's
// stock.sector now matches a friend's separately-built tool's display
// taxonomy (Nifty 50 / Bank / Fin Service / etc.), which is too coarse for
// scoring. Mirrors backend/app/config.py's INDUSTRY_GROUP exactly (same
// intentional-duplication precedent as this file's own momentumScore.js).
export const INDUSTRY_GROUP = {
  // Energy
  "BPCL": "Energy",
  "COALINDIA": "Energy",
  "GAIL": "Energy",
  "HINDPETRO": "Energy",
  "IOC": "Energy",
  "OIL": "Energy",
  "ONGC": "Energy",
  "PETRONET": "Energy",
  "RELIANCE": "Energy",
  // Power
  "ADANIENSOL": "Power",
  "ADANIGREEN": "Power",
  "ADANIPOWER": "Power",
  "INOXWIND": "Power",
  "IREDA": "Power",
  "JSWENERGY": "Power",
  "NHPC": "Power",
  "NTPC": "Power",
  "POWERGRID": "Power",
  "PREMIERENE": "Power",
  "SUZLON": "Power",
  "TATAPOWER": "Power",
  "WAAREEENER": "Power",
  // Capital Goods
  "ABB": "Capital Goods",
  "ASTRAL": "Capital Goods",
  "BDL": "Capital Goods",
  "BEL": "Capital Goods",
  "BHEL": "Capital Goods",
  "CGPOWER": "Capital Goods",
  "COCHINSHIP": "Capital Goods",
  "CUMMINSIND": "Capital Goods",
  "GVT&D": "Capital Goods",
  "HAL": "Capital Goods",
  "KEI": "Capital Goods",
  "LT": "Capital Goods",
  "MAZDOCK": "Capital Goods",
  "POLYCAB": "Capital Goods",
  "POWERINDIA": "Capital Goods",
  "SIEMENS": "Capital Goods",
  "SOLARINDS": "Capital Goods",
  // Consumer Durables
  "AMBER": "Consumer Durables",
  "BLUESTARCO": "Consumer Durables",
  "CROMPTON": "Consumer Durables",
  "DIXON": "Consumer Durables",
  "HAVELLS": "Consumer Durables",
  "PGEL": "Consumer Durables",
  "TITAN": "Consumer Durables",
  "VOLTAS": "Consumer Durables",
  // Infra
  "ADANIPORTS": "Infra",
  "CONCOR": "Infra",
  "DELHIVERY": "Infra",
  "GMRAIRPORT": "Infra",
  "RVNL": "Infra",
  // Auto
  "ASHOKLEY": "Auto",
  "BAJAJ-AUTO": "Auto",
  "BHARATFORG": "Auto",
  "BOSCHLTD": "Auto",
  "EICHERMOT": "Auto",
  "EXIDEIND": "Auto",
  "FORCEMOT": "Auto",
  "HEROMOTOCO": "Auto",
  "HYUNDAI": "Auto",
  "M&M": "Auto",
  "MARUTI": "Auto",
  "MOTHERSON": "Auto",
  "SONACOMS": "Auto",
  "TIINDIA": "Auto",
  "TMPV": "Auto",
  "TVSMOTOR": "Auto",
  "UNOMINDA": "Auto",
  // Pvt Banks
  "AUBANK": "Pvt Banks",
  "AXISBANK": "Pvt Banks",
  "BANDHANBNK": "Pvt Banks",
  "FEDERALBNK": "Pvt Banks",
  "HDFCBANK": "Pvt Banks",
  "ICICIBANK": "Pvt Banks",
  "IDFCFIRSTB": "Pvt Banks",
  "INDUSINDBK": "Pvt Banks",
  "KOTAKBANK": "Pvt Banks",
  "RBLBANK": "Pvt Banks",
  "YESBANK": "Pvt Banks",
  // PSU Banks
  "BANKBARODA": "PSU Banks",
  "BANKINDIA": "PSU Banks",
  "CANBK": "PSU Banks",
  "INDIANB": "PSU Banks",
  "PNB": "PSU Banks",
  "SBIN": "PSU Banks",
  "UNIONBANK": "PSU Banks",
  // NBFC
  "ABCAPITAL": "NBFC",
  "BAJAJFINSV": "NBFC",
  "BAJFINANCE": "NBFC",
  "CHOLAFIN": "NBFC",
  "HDFCAMC": "NBFC",
  "IRFC": "NBFC",
  "JIOFIN": "NBFC",
  "LICHSGFIN": "NBFC",
  "LTF": "NBFC",
  "MANAPPURAM": "NBFC",
  "MFSL": "NBFC",
  "MUTHOOTFIN": "NBFC",
  "PFC": "NBFC",
  "PNBHOUSING": "NBFC",
  "RECLTD": "NBFC",
  "SBICARD": "NBFC",
  "SHRIRAMFIN": "NBFC",
  // Insurance
  "HDFCLIFE": "Insurance",
  "ICICIGI": "Insurance",
  "ICICIPRULI": "Insurance",
  "LICI": "Insurance",
  "SBILIFE": "Insurance",
  // Capital Markets
  "360ONE": "Capital Markets",
  "ANGELONE": "Capital Markets",
  "BSE": "Capital Markets",
  "CDSL": "Capital Markets",
  "IEX": "Capital Markets",
  "MCX": "Capital Markets",
  "MOTILALOFS": "Capital Markets",
  "NAM-INDIA": "Capital Markets",
  "NAUKRI": "Capital Markets",
  "NUVAMA": "Capital Markets",
  "PAYTM": "Capital Markets",
  "POLICYBZR": "Capital Markets",
  // Healthcare
  "APOLLOHOSP": "Healthcare",
  "MAXHEALTH": "Healthcare",
  // Realty
  "DLF": "Realty",
  "GODREJPROP": "Realty",
  "LODHA": "Realty",
  "NBCC": "Realty",
  "OBEROIRLTY": "Realty",
  "PHOENIXLTD": "Realty",
  "PRESTIGE": "Realty",
  // IT
  "CAMS": "IT",
  "COFORGE": "IT",
  "HCLTECH": "IT",
  "INFY": "IT",
  "KAYNES": "IT",
  "KFINTECH": "IT",
  "KPITTECH": "IT",
  "LTM": "IT",
  "MPHASIS": "IT",
  "OFSS": "IT",
  "PERSISTENT": "IT",
  "TATAELXSI": "IT",
  "TCS": "IT",
  "TECHM": "IT",
  "WIPRO": "IT",
  // Pharma
  "ALKEM": "Pharma",
  "AUROPHARMA": "Pharma",
  "BIOCON": "Pharma",
  "CIPLA": "Pharma",
  "DIVISLAB": "Pharma",
  "DRREDDY": "Pharma",
  "FORTIS": "Pharma",
  "GLENMARK": "Pharma",
  "LAURUSLABS": "Pharma",
  "LUPIN": "Pharma",
  "MANKIND": "Pharma",
  "SUNPHARMA": "Pharma",
  "TORNTPHARM": "Pharma",
  "ZYDUSLIFE": "Pharma",
  // Chemicals
  "PIDILITIND": "Chemicals",
  "PIIND": "Chemicals",
  "SRF": "Chemicals",
  "UPL": "Chemicals",
  // Consumer
  "INDHOTEL": "Consumer",
  "JUBLFOOD": "Consumer",
  "PAGEIND": "Consumer",
  // FMCG
  "ASIANPAINT": "FMCG",
  "BRITANNIA": "FMCG",
  "COLPAL": "FMCG",
  "DABUR": "FMCG",
  "DMART": "FMCG",
  "ETERNAL": "FMCG",
  "GODFRYPHLP": "FMCG",
  "GODREJCP": "FMCG",
  "HINDUNILVR": "FMCG",
  "ITC": "FMCG",
  "KALYANKJIL": "FMCG",
  "MARICO": "FMCG",
  "NESTLEIND": "FMCG",
  "NYKAA": "FMCG",
  "PATANJALI": "FMCG",
  "RADICO": "FMCG",
  "SUPREMEIND": "FMCG",
  "SWIGGY": "FMCG",
  "TATACONSUM": "FMCG",
  "UNITDSPR": "FMCG",
  "VBL": "FMCG",
  // Cement
  "AMBUJACEM": "Cement",
  "DALBHARAT": "Cement",
  "SHREECEM": "Cement",
  "ULTRACEMCO": "Cement",
  // Metals
  "ADANIENT": "Metals",
  "APLAPOLLO": "Metals",
  "HINDALCO": "Metals",
  "HINDZINC": "Metals",
  "JINDALSTEL": "Metals",
  "JSWSTEEL": "Metals",
  "NATIONALUM": "Metals",
  "NMDC": "Metals",
  "SAIL": "Metals",
  "TATASTEEL": "Metals",
  "VEDL": "Metals",
  // Telecom
  "BHARTIARTL": "Telecom",
  "IDEA": "Telecom",
  "INDUSTOWER": "Telecom",
  // Aviation
  "INDIGO": "Aviation",
  // Retail
  "TRENT": "Retail",
  "VMM": "Retail",
  // Diversified
  "BAJAJHLDNG": "Diversified",
  "GRASIM": "Diversified",
};

export function industryGroup(symbol) {
  return INDUSTRY_GROUP[symbol] || "";
}
